--CRIAR UMA PROCEDURE QUE RECEBE UM VALOR EM REAIS E A MOEDA (EU, DO, LI) QUE A PESSOA DESEJA CONVERTER
--COM BASE NA MOEDA ESCOLHIDA EFETUE A CONVERSÃO E RETORNE O VALOR ORIGINAL, O CONVERTIDO E
--A DESCRIÇÃO DA MOEDA ESCOLHIDA.
USE MinhaCaixa;

GO

CREATE TABLE CONVERCAO (
	ID INT NOT NULL IDENTITY(1, 1) CONSTRAINT PK_CONVERCAO PRIMARY KEY,
	VALORORIGINAL MONEY,
	VALORCONVERTIDO MONEY,
	MOEDA CHAR(2)
)

GO

CREATE PROCEDURE procConverteMoedas
@VALOR MONEY, @MOEDA CHAR(2)
AS
BEGIN
	DECLARE @VALORCONVERTIDO INT
	IF (@MOEDA = 'EU') BEGIN
		SET @VALORCONVERTIDO = @VALOR / 4.38;
		INSERT CONVERCAO (VALORORIGINAL, VALORCONVERTIDO, MOEDA)
		VALUES (@VALOR, @VALORCONVERTIDO, @MOEDA);
	END ELSE IF (@MOEDA = 'DO') BEGIN
		SET @VALORCONVERTIDO = @VALOR / 3.80;
		INSERT CONVERCAO (VALORORIGINAL, VALORCONVERTIDO, MOEDA)
		VALUES (@VALOR, @VALORCONVERTIDO, @MOEDA);
	END ELSE IF (@MOEDA = 'LI') BEGIN
		SET @VALORCONVERTIDO = @VALOR / 4.88;
		INSERT CONVERCAO (VALORORIGINAL, VALORCONVERTIDO, MOEDA)
		VALUES (@VALOR, @VALORCONVERTIDO, @MOEDA);
	END

	DECLARE @PK INT
	SET @PK = (SELECT @@IDENTITY)

	SELECT * FROM CONVERCAO WHERE ID = @PK;
END

EXEC procConverteMoedas 50, 'DO';

SELECT * FROM CONVERCAO;