-- CRIE UMA FUNÇÃO QUE TRAGA O SALDO
-- TOTAL DO CLIENTE CONVERTIDO EM DOLAR
-- USE A CONTA DO CLIENTE COMO PARAMETRO DE ENTRADA

USE MinhaCaixa;

CREATE FUNCTION fnConverteDolar (@conta INT)
RETURNS DOUBLE
AS
BEGIN
	SELECT SUM(MovimentoValor) FROM Movimentos WHERE ContaNumero = @conta;
END
