use Gabriel

CREATE TABLE ALUNO (
	ALUNOID INT CONSTRAINT PK_ALUNOID PRIMARY KEY,
	ALUNONOME VARCHAR(50),
	ALUNOSOBRENOME VARCHAR(50)
)

GO

INSERT ALUNO (ALUNOID, ALUNONOME, ALUNOSOBRENOME) VALUES (1, 'GABRIEL', 'BUSARELLO')

GO

INSERT ALUNO (ALUNOSOBRENOME, ALUNONOME, ALUNOID) VALUES ('SARUKAUA', 'NATAMI', 2)

GO

INSERT ALUNO VALUES (3, 'SARUKAUA', 'NATAMI') -- NÃO FAZER!

GO

CREATE TABLE ALUNO2 (
	ALUNOID INT IDENTITY(1,1) CONSTRAINT PK_ALUNOID2 PRIMARY KEY,
	ALUNONOME VARCHAR(50),
	ALUNOSOBRENOME VARCHAR(50)
)

GO

INSERT ALUNO2 (ALUNONOME, ALUNOSOBRENOME) VALUES ('GABRIEL', 'BUSARELLO')

GO

ALTER TABLE ALUNO2 ALTER COLUMN ALUNONOME VARCHAR(50) NOT NULL
ALTER TABLE ALUNO2 ALTER COLUMN ALUNOSOBRENOME VARCHAR(50) NOT NULL

GO

